version: "3.3"
services:
  api:
    image: 10881069829.dkr.ecr.ap-northeast-2.amazonaws.com/libido-dev:0.0.1
    container_name: libido_api
    build: .
    restart: always
    environment:
      CACHES_BACKEND: "django_redis.cache.RedisCache"
      CACHES_KEY_PREFIX: "LIBIDO:API"
      CACHES_LOCATION: "redis://redis:6379/1"
      DATABASE_ENGINE: "${DATABASE_ENGINE}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USER: "${DATABASE_USER}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD} 
      SERVICE_ENV: "development"
      SERVICE_SERVER_DOMAIN_OR_IP: ''

    links:
      - redis:redis

    ports:
     - 80:80
     - 443:443

    restart: always

  redis:
    image: redis:6.2.1
    container_name: libido_redis
    command: redis-server --port 6379
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"

    ports:
      - 6379:6379
    expose:
      - "6379"

    restart: always
