# Generated by Django 3.2.12 on 2022-02-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libido_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_recruiter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
