# Generated by Django 3.2.12 on 2022-02-09 18:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('libido_users', '0005_auto_20220209_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='KR', help_text='국가 필드', max_length=2),
        ),
    ]
