# Generated by Django 3.2.12 on 2022-02-15 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("libido_users", "0006_alter_user_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_email",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("key", models.CharField(blank=True, max_length=50, null=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 인증",
                "verbose_name_plural": "이메일 인증 모음",
                "db_table": "email_auth",
                "managed": True,
            },
        ),
    ]
