# Generated by Django 3.2.12 on 2022-02-16 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("libido_users", "0007_emailauth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False, help_text="수락 상태")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        help_text="수신자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="발송자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "초대장",
                "verbose_name_plural": "초대장 모음",
                "db_table": "invitation",
                "managed": True,
            },
        ),
    ]
