# Generated by Django 3.2.12 on 2022-03-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libido_users", "0009_invitation_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agree_marketing",
            field=models.BooleanField(
                blank=True, default=False, help_text="마케팅 수신동의", null=True
            ),
        ),
    ]
