# Generated by Django 3.2.12 on 2022-02-11 05:26

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import libido_contents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='방 설명', null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=50, null=True)),
                ('thumb', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=libido_contents.models.upload_thumb)),
                ('running_time', models.TimeField(blank=True, help_text='러닝타임', null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, help_text='삭제한 시간', null=True)),
            ],
            options={
                'verbose_name': '콘텐츠',
                'verbose_name_plural': '콘텐츠 모음',
                'db_table': 'content',
                'managed': True,
            },
        ),
    ]
