# Generated by Django 3.2.12 on 2022-02-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libido_contents", "0002_auto_20220211_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="url",
            field=models.URLField(blank=True, max_length=550, null=True, unique=True),
        ),
    ]
