# Generated by Django 3.2.12 on 2022-02-15 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("libido_contents", "0003_alter_content_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="장르 이름", max_length=50, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "장르",
                "verbose_name_plural": "장르 모음",
                "db_table": "genre",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ContentGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        help_text="콘텐츠",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contentgenre_content",
                        to="libido_contents.content",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        help_text="장르",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contentgenre_genre",
                        to="libido_contents.genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "콘텐츠 장르",
                "verbose_name_plural": "콘텐츠 장르 모음",
                "db_table": "content_genre",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="content",
            name="genre",
            field=models.ManyToManyField(
                blank=True,
                help_text="콘텐츠 장르",
                through="libido_contents.ContentGenre",
                to="libido_contents.Genre",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentgenre",
            constraint=models.UniqueConstraint(
                fields=("content", "genre"), name="unique_content_genre"
            ),
        ),
    ]
