# Generated by Django 3.2.12 on 2022-02-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libido_contents', '0005_usercontenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
