# Generated by Django 3.2.12 on 2022-02-18 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("libido_contents", "0006_alter_content_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontenthistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="유저",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usercontenthistory_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
