# Generated by Django 3.2.12 on 2022-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libido_contents", "0007_usercontenthistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="idx",
            field=models.PositiveIntegerField(
                blank=True, help_text="(유투브전용) 인덱스", null=True
            ),
        ),
    ]
