# Generated by Django 3.2.12 on 2022-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libido_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, help_text='비밀번호', max_length=250, null=True),
        ),
    ]
