# Generated by Django 3.2.12 on 2022-02-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libido_rooms', '0002_alter_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='룸 카테고리들', through='libido_rooms.RoomCategory', to='libido_rooms.Category'),
        ),
    ]
