# Generated by Django 3.2.12 on 2022-02-11 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libido_contents', '0001_initial'),
        ('libido_rooms', '0004_auto_20220210_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content', models.ForeignKey(blank=True, help_text='콘텐츠', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomcontent_content', to='libido_contents.content')),
                ('room', models.ForeignKey(blank=True, help_text='스트리밍 방', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roomcontent_room', to='libido_rooms.room')),
            ],
            options={
                'verbose_name': '방 콘텐츠',
                'verbose_name_plural': '방 콘텐츠 모음',
                'db_table': 'room_content',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='contents',
            field=models.ManyToManyField(blank=True, help_text='룸 콘텐츠', through='libido_rooms.RoomContent', to='libido_contents.Content'),
        ),
        migrations.AddConstraint(
            model_name='roomcontent',
            constraint=models.UniqueConstraint(fields=('content', 'room'), name='unique_content_room'),
        ),
    ]
