# Generated by Django 3.2.12 on 2022-02-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libido_rooms", "0006_room_play_lists_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="platform",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "유투브"), (2, "넷플릭스"), (3, "공중파 ")],
                default=1,
                help_text="영상 플랫폼",
                null=True,
            ),
        ),
    ]
