# Generated by Django 3.2.12 on 2022-02-16 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("libido_rooms", "0007_room_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="스트리밍 방",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roomuser_room",
                        to="libido_rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="참여자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roomuser_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "방 참여자",
                "verbose_name_plural": "방 참여자 모음",
                "db_table": "room_user",
                "managed": True,
            },
        ),
        migrations.AddConstraint(
            model_name="roomuser",
            constraint=models.UniqueConstraint(
                fields=("user", "room"), name="unique_room_user"
            ),
        ),
    ]
