# Generated by Django 3.2.12 on 2022-03-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libido_rooms", "0009_room_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_play_content_id",
            field=models.CharField(
                blank=True, help_text="현 재생중인 콘텐츠 아이디", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="current_play_time",
            field=models.TimeField(blank=True, help_text="현 재생중인 콘텐츠 시간", null=True),
        ),
    ]
