# Generated by Django 3.2.12 on 2022-04-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libido_rooms", "0011_room_current_play_ts"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_dm",
            field=models.BooleanField(default=False, help_text="DM 여부"),
        ),
    ]
