# Generated by Django 3.2.12 on 2022-02-19 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libido_rooms", "0009_room_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="메세지 작성한 시간",
                        verbose_name="작성한 시간",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="스트리밍 방",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_room",
                        to="libido_rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메세지",
                "verbose_name_plural": "채팅 메세지 모음",
                "db_table": "message",
                "ordering": ["created_at"],
                "managed": True,
            },
        ),
    ]
