# Generated by Django 3.2.12 on 2022-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libido_chats", "0003_auto_20220220_0148"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "managed": True,
                "ordering": ["-id", "-created_at"],
                "verbose_name": "채팅 메세지",
                "verbose_name_plural": "채팅 메세지 모음",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
