# Generated by Django 3.2.12 on 2022-03-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libido_chats", "0004_auto_20220220_0232"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "managed": True,
                "ordering": ["-id"],
                "verbose_name": "채팅 메세지",
                "verbose_name_plural": "채팅 메세지 모음",
            },
        ),
    ]
